### Defaults ###
modkey = "Mod4"
mousekey = "Mod4"
workspaces = []
tags = ["1", "2", "3", "4", "5"]
layouts = ["MainAndVertStack"]
disable_current_tag_swap = true
focus_behaviour = "Sloppy"
focus_new_windows = true

### Window Rules ###
window_rules = [
	{window_class = "discord", spawn_on_tag = 2},
	{window_class = "pentablet", spawn_on_tag = 5, spawn_floating = true}
]

### Scratchpads ###
[[scratchpad]]
name = "Alacritty"
value = "alacritty"
[[keybind]]
command = "ToggleScratchPad"
value = "Alacritty"
modifier = ["modkey"]
key = "Return"
[[scratchpad]]
name = "Bottom"
value = "alacritty -e btm"
[[keybind]]
command = "ToggleScratchPad"
value = "Bottom"
modifier = ["modkey", "Shift"]
key = "Escape"

### Rofi ###
[[keybind]]
command = "Execute"
value = "rofi -show drun"
modifier = ["modkey"]
key = "p"
[[keybind]]
command = "Execute"
value = "rofi -show window"
modifier = ["modkey"]
key = "Tab"

### Spawn Terminal ###
[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["modkey", "Shift"]
key = "Return"

### Close Window ###
[[keybind]]
command = "CloseWindow"
modifier = ["modkey", "Shift"]
key = "c"

### Reload ###
[[keybind]]
command = "SoftReload"
modifier = ["modkey"]
key = "q"
[[keybind]]
command = "Execute"
value = "loginctl kill-session $XDG_SESSION_ID"
modifier = ["modkey", "Shift"]
key = "q"

### Focus Window ###
[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "k"
[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "j"

### Move Window ###
[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "k"
[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "j"
[[keybind]]
command = "MoveWindowTop"
modifier = ["modkey", "Shift"]
key = "t"

### Resize Window ###
[[keybind]]
command = "IncreaseMainWidth"
value = "5"
modifier = ["modkey", "Shift"]
key = "l"
[[keybind]]
command = "DecreaseMainWidth"
value = "5"
modifier = ["modkey", "Shift"]
key = "h"

### Layouts ###
[[keybind]]
command = "ToggleFullScreen"
modifier = ["modkey"]
key = "f"

### Focus Workspace ###
[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "l"
[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "h"

### Go To Tags ###
[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"
[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"
[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"
[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"
[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

### Move Window To Tag ###
[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "1"
[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "2"
[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "3"
[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"
[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "5"

### Volume ###
[[keybind]]
command = "Execute"
value = "scripts/volume -u"
modifier = []
key = "XF86XK_AudioRaiseVolume"
[[keybind]]
command = "Execute"
value = "scripts/volume -d"
modifier = []
key = "XF86XK_AudioLowerVolume"
[[keybind]]
command = "Execute"
value = "scripts/volume -m"
modifier = []
key = "XF86XK_AudioMute"

### Screenshot ###
[[keybind]]
command = "Execute"
value = "scripts/screenshot -a"
modifier = []
key = "Print"
[[keybind]]
command = "Execute"
value = "scripts/screenshot -f"
modifier = ["modkey"]
key = "Print"
