### Defaults ###
modkey = "Mod4"
mousekey = "Mod4"
workspaces = []
tags = ["1", "2", "3", "4", "5"]
layouts = ["Fibonacci"]
disable_current_tag_swap = false
focus_behaviour = "Sloppy"
focus_new_windows = true

### Scratchpad ###
[[scratchpad]]
name = "Kitty"
value = "kitty"

[[keybind]]
command = "ToggleScratchPad"
value = "Kitty"
modifier = ["modkey"]
key = "Return"

### Rofi ###
[[keybind]]
command = "Execute"
value = "rofi -show drun -icon-theme Flatery-Blue-Dark"
modifier = ["modkey"]
key = "p"

### Spawn Terminal ###
[[keybind]]
command = "Execute"
value = "kitty"
modifier = ["modkey", "Shift"]
key = "Return"

### Close Window ###
[[keybind]]
command = "CloseWindow"
modifier = ["modkey", "Shift"]
key = "c"

### Reload ###
[[keybind]]
command = "SoftReload"
modifier = ["modkey"]
key = "q"

[[keybind]]
command = "Execute"
value = "loginctl kill-session $XDG_SESSION_ID"
modifier = ["modkey", "Shift"]
key = "q"

### Move Window ###
[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "MoveWindowTop"
modifier = ["modkey", "Shift"]
key = "t"

### Focus Window ###
[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "j"

### Layouts ###
[[keybind]]
command = "NextLayout"
modifier = ["modkey"]
key = "Space"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "Space"

### Focus Workspace ###
[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "h"

### Go To Tags ###
[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

### Move Window To Tag ###
[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "5"

### Volume ###
[[keybind]]
command = "Execute"
value = "pactl set-sink-volume bluez_sink.5C_C6_E9_14_A8_15.a2dp_sink +5%"
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "Execute"
value = "pactl set-sink-volume bluez_sink.5C_C6_E9_14_A8_15.a2dp_sink -5%"
modifier = ["modkey", "Control"]
key = "Down"

[[keybind]]
command = "Execute"
value = "pactl set-sink-mute bluez_sink.5C_C6_E9_14_A8_15.a2dp_sink toggle"
modifier = ["modkey", "Shift", "Control"]
key = "Down"

[[keybind]]
command = "Execute"
value = "pactl set-sink-volume alsa_output.pci-0000_00_1b.0.analog-stereo +5%"
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "Execute"
value = "pactl set-sink-volume alsa_output.pci-0000_00_1b.0.analog-stereo -5%"
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "Execute"
value = "pactl set-sink-mute alsa_output.pci-0000_00_1b.0.analog-stereo toggle"
modifier = ["modkey", "Shift"]
key = "Down"

### Screenshot ###
[[keybind]]
command = "Execute"
value = "maim -usb 2 | xclip -selection clipboard -t image/png && notify-send 'Screenshot Selected!'"
modifier = []
key = "Print"

[[keybind]]
command = "Execute"
value = "maim -u /mnt/HDD/Images/Screenshots/maim-$(date +%m-%d-%T).png && notify-send 'Screenshot Captured!'"
modifier = ["modkey"]
key = "Print"
