### Defaults ###
modkey = "Mod4"
mousekey = "Mod4"
workspaces = []
tags = ["1", "2", "3", "4", "5"]
layouts = ["MainAndVertStack"]
disable_current_tag_swap = false
focus_behaviour = "Sloppy"
focus_new_windows = true

### Scratchpads ###
[[scratchpad]]
name = "Kitty"
value = "kitty"
[[keybind]]
command = "ToggleScratchPad"
value = "Kitty"
modifier = ["modkey"]
key = "Return"
[[scratchpad]]
name = "Bottom"
value = "kitty btm"
[[keybind]]
command = "ToggleScratchPad"
value = "Bottom"
modifier = ["modkey", "Shift"]
key = "Escape"

### Rofi ###
[[keybind]]
command = "Execute"
value = "rofi -show drun"
modifier = ["modkey"]
key = "p"

### Spawn Terminal ###
[[keybind]]
command = "Execute"
value = "kitty"
modifier = ["modkey", "Shift"]
key = "Return"

### Close Window ###
[[keybind]]
command = "CloseWindow"
modifier = ["modkey", "Shift"]
key = "c"

### Reload ###
[[keybind]]
command = "SoftReload"
modifier = ["modkey"]
key = "q"
[[keybind]]
command = "Execute"
value = "loginctl kill-session $XDG_SESSION_ID"
modifier = ["modkey", "Shift"]
key = "q"

### Focus Window ###
[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "k"
[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "j"

### Move Window ###
[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "k"
[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "j"
[[keybind]]
command = "MoveWindowTop"
modifier = ["modkey", "Shift"]
key = "t"

### Resize Window ###
[[keybind]]
command = "IncreaseMainWidth"
value = "5"
modifier = ["modkey", "Shift"]
key = "l"
[[keybind]]
command = "DecreaseMainWidth"
value = "5"
modifier = ["modkey", "Shift"]
key = "h"

### Layouts ###
[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "Tab"
[[keybind]]
command = "NextLayout"
modifier = ["modkey"]
key = "Tab"
[[keybind]]
command = "ToggleFullScreen"
modifier = ["modkey"]
key = "f"

### Focus Workspace ###
[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "l"
[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "h"

### Go To Tags ###
[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"
[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"
[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"
[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"
[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

### Move Window To Tag ###
[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "1"
[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "2"
[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "3"
[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"
[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "5"

### Volume ###
[[keybind]]
command = "Execute"
value = "amixer -D pulse sset Master 5%+"
modifier = ["modkey"]
key = "Up"
[[keybind]]
command = "Execute"
value = "amixer -D pulse sset Master 5%-"
modifier = ["modkey"]
key = "Down"
[[keybind]]
command = "Execute"
value = "amixer -D pulse sset Master toggle"
modifier = ["modkey", "Shift"]
key = "Down"

### Screenshot ###
[[keybind]]
command = "Execute"
value = "maim -usb 2 /tmp/clipboard.png; sleep .1; xclip -selection clipboard < /tmp/clipboard.png -t image/png && notify-send -i /tmp/clipboard.png 'Screenshot' 'Selection Captured'"
modifier = []
key = "Print"
