# Specifies the network interface to use for the LocalIP readout
interface = "wlan0"

# Lengthen uptime format
long_uptime = false

# Lengthen shell output
long_shell = false

# Lengthen shell output
long_kernel = false

# Toggle between the current shell or the default one
# This feature has not yet landed in a release, only uncomment if using upstream
current_shell = true 

# Specify the theme to use
# Accepted values (case-insensitive):
#   - Hydrogen
#   - Helium
#   - Lithium
#   - Beryllium
#   - Boron
#
# Custom themes are also supported, they
# need to be placed in $XDG_CONFIG_DIR for
# macchina to find and parse them.
#theme = "Bliss"

# Displays only the specified readouts.
# Conflicts with: hide
# Accepted values (case-sensitive):
#   - Host
#   - Machine
#   - Kernel
#   - Distribution
#   - OperatingSystem
#   - DesktopEnvironment
#   - WindowManager
#   - Resolution
#   - Backlight
#   - Packages
#   - LocalIP
#   - Terminal
#   - Shell
#   - Uptime
#   - Processor
#   - ProcessorLoad
#   - Memory
#   - Battery
# Example:
#   show = ["Battery", "Memory", ...]
show = ["Distribution", "Packages", "WindowManager", "Terminal"]
